config/routes.rb
Rails.application.routes.draw do

  root 'lists#dashboard'

  match '/lists/dashboard', :to => 'lists#dashboard', :via => [:get, :post]
  match '/lists/new', :to => 'lists#new', :via => [:get, :post]
  match '/lists/view/:list_id', :to => 'lists#view', :via => [:get, :post], :as => 'lists_view'

  match '/items/new/:list_id', :to => 'items#new', :via => [:get, :post], :as => 'items_new'

  resources :lists
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @list_id = params[:list_id]
    @item = Item.new
  end

  def create
    @item = Item.new(params.require(:item).permit(:name,:list_id))
    if @item.save
      redirect_to lists_view_path(:list_id => @item.list_id)
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to :back
  end

  def delete
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def dashboard
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params.require(:list).permit(:name))
    if @list.save
      redirect_to lists_dashboard_url
    end
  end

  def view

    @list_id = params[:list_id]
    @list = List.find_by(id: @list_id)
    @items = @list.items
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to :back
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/new.html.erb
<%= form_for @item do |f| %>
    <div>
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.hidden_field :list_id,:value => @list_id%>
    </div>
    <br>
    <%= f.submit 'Add New Item', class: 'btn btn-primary'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/dashboard.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <th><h2>Name</h2></th>
        <th><h2>Delete</h2></th>
      </thead>
      <% @lists.each do |list| %>
            <tr>
              <td class="col-md-6"><h1><%= link_to list.name, lists_view_path(:list_id => list.id), :class => 'btn btn-block btn-success btn-lg'%></h1></td>
              <td class="col-md-2"><%=link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs pull-right'%></td>
            </tr>
      <%end unless @lists.blank?%>
    </table>
  </div>
</div>
  <%= link_to 'New List', lists_new_path, :class => 'btn btn-block btn-primary'%>

app/views/lists/new.html.erb
<%= form_for @list do |f| %>
    <div>
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </div>
    <br>
    <%= f.submit 'Add New List', class: 'btn btn-primary'%>
<% end %>

app/views/lists/view.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <table class="table table-striped table-hover">
      <thead>
      <th><h2>Name</h2></th>
      <th><h2>Delete</h2></th>
      </thead>
      <% @items.each do |item| %>
          <tr>
            <td class="col-md-6"><h1><%=item.name%></h1></td>
            <td class="col-md-2"><%=link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs pull-right'%></td>
          </tr>
      <%end unless @items.blank?%>
    </table>
  </div>
</div>

<%= link_to 'New Item', items_new_path(:list_id => @list_id),:class => 'btn btn-block btn-primary'%>